kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: slack_demo
      group_by: ['alertname', 'priority']
      group_wait: 1s
      repeat_interval: 30m
      routes:
        - receiver: slack_demo
          # Send severity=slack alerts to slack.
          match:
            severity: slack
          group_wait: 1s
          repeat_interval: 1m
 
    receivers:
    - name: slack_demo
      slack_configs:
      - api_url: https://hooks.slack.com/services/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
        channel: '#proj-alert'
