# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Install any needed packages specified in requirements.txt
# Note: Ensure you have a requirements.txt file with Flask and pymongo
RUN pip install --no-cache-dir -r requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable
ENV MONGO_HOST=localhost
ENV MONGO_PORT=27017

# Run app.py when the container launches
CMD ["python", "app.py"]
